language: csharp
mono: none
dotnet: 2.1.502
solution: Cactus.Blade.Threading.sln
install:
  - dotnet restore
script:
  - dotnet msbuild /p:Configuration=Release Cactus.Blade.Threading.sln
  - dotnet restore
  - dotnet test Threading.Test/Threading.Test.csproj
